name: pre-commit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install go-sec
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest
    - name: Install go-returns
      run: go install github.com/sqs/goreturns@latest
    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.2
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.6
    - name: Add Go to PATH
      run: echo "PATH=$PATH:/home/runner/go/bin" >> $GITHUB_ENV
    - uses: pre-commit/action@v3.0.1